# Generated by Django 2.0 on 2018-01-18 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(verbose_name='date published')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('views', models.IntegerField(default=0)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('reg_date', models.DateTimeField(verbose_name='date registered')),
            ],
        ),
        migrations.CreateModel(
            name='Trip_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trips_tittle', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('file', models.FileField(null=True, upload_to='trip_media')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceVote',
            fields=[
                ('trip_vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trips.Trip_Event')),
                ('vote_recommended', models.IntegerField(default=0)),
                ('vote_not_recommended', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='trip_event',
            name='trip_destination',
            field=models.ManyToManyField(default='', to='trips.Destination'),
        ),
        migrations.AddField(
            model_name='trip_event',
            name='trip_owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trips.Owner'),
        ),
        migrations.AddField(
            model_name='participant',
            name='trip_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip_Event'),
        ),
        migrations.AddField(
            model_name='choice',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip_Event'),
        ),
    ]
