# Generated by Django 2.0 on 2018-01-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('reg_date', models.DateTimeField(verbose_name='date published')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='subdestination',
            name='subdestination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Destination'),
        ),
    ]
